declare module 'lunar-javascript' {
  export interface LunarInstance {
    getYear(): number;
    getMonth(): number;
    getDay(): number;
    getHour(): number;
    getMinute(): number;
    getSecond(): number;
    getYearGan(): string;
    getYearZhi(): string;
    getMonthGan(): string;
    getMonthZhi(): string;
    getDayGan(): string;
    getDayZhi(): string;
    getTimeGan(): string;
    getTimeZhi(): string;
    getYearNaYin(): string;
    getMonthNaYin(): string;
    getDayNaYin(): string;
    getTimeNaYin(): string;
    getYearShengXiao(): string;
    getMonthShengXiao(): string;
    getDayShengXiao(): string;
    getTimeShengXiao(): string;
    getYearXun(): string;
    getMonthXun(): string;
    getDayXun(): string;
    getTimeXun(): string;
    getYearXunKong(): string;
    getMonthXunKong(): string;
    getDayXunKong(): string;
    getTimeXunKong(): string;
    getYearShiShen(): string;
    getMonthShiShen(): string;
    getDayShiShen(): string;
    getTimeShiShen(): string;
    getYearShenSha(): string[];
    getMonthShenSha(): string[];
    getDayShenSha(): string[];
    getTimeShenSha(): string[];
    getYearTouGan(): string;
    getMonthTouGan(): string;
    getDayTouGan(): string;
    getTimeTouGan(): string;
    getYearZhi(): string;
    getMonthZhi(): string;
    getDayZhi(): string;
    getTimeZhi(): string;
    getYearGan(): string;
    getMonthGan(): string;
    getDayGan(): string;
    getTimeGan(): string;
    getYearNaYin(): string;
    getMonthNaYin(): string;
    getDayNaYin(): string;
    getTimeNaYin(): string;
    getYearShengXiao(): string;
    getMonthShengXiao(): string;
    getDayShengXiao(): string;
    getTimeShengXiao(): string;
    getYearXun(): string;
    getMonthXun(): string;
    getDayXun(): string;
    getTimeXun(): string;
    getYearXunKong(): string;
    getMonthXunKong(): string;
    getDayXunKong(): string;
    getTimeXunKong(): string;
    getYearShiShen(): string;
    getMonthShiShen(): string;
    getDayShiShen(): string;
    getTimeShiShen(): string;
    getYearShenSha(): string[];
    getMonthShenSha(): string[];
    getDayShenSha(): string[];
    getTimeShenSha(): string[];
  }

  export const Lunar: {
    fromYmd(year: number, month: number, day: number): LunarInstance;
    fromYmdHms(year: number, month: number, day: number, hour: number, minute: number, second: number): LunarInstance;
    fromDate(date: Date): LunarInstance;
  };
}
